### ISSUE TITLE
Your VS Code extension is affected by a security issue

### ISSUE THREAD

**Issue by auchenberg** [maziac/z80-debug#1]
Hi,

Kenneth here from the VS Code team.

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream,

We will need to take action to block your extension if your extension isn't updated in a reasonable timeframe.

Please get in touch at kennau@microsoft.com

/k

**Comment by maziac** [comment]
Hi,I got the e-mail below. You asked to get in touch.Is my extension already unlisted?What are the next steps/what are you expecting from me?How can I check myself If my extension is not affected anymore?BR,ThomasAm 28.11.2018 03:59 schrieb Kenneth Auchenberg <notifications@github.com>:Hi,
Kenneth here from the VS Code team.
Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream,
We will need to take action to block your extension if your extension isn't updated in a reasonable timeframe.
Please get in touch at kennau@microsoft.com
/k

**Comment by auchenberg** [comment]
Your extension is shipping the module `flatmap-stream v0.1.0` which is marked as malware. Please check your dependencies by running `npm ls event-stream flatmap-stream` and remove the dependencies.

**Comment by auchenberg** [comment]
Wonderful, thanks thomas!
