### ISSUE TITLE
Step-by-step instruction

### ISSUE THREAD

**Issue by vito-Z80** [maziac/z80-debug#5]
Could you make the documentation more detailed? I know z80, but I don’t know how to combine everything into a single whole to make it work?
Please create a "step by step".

(ctrl+shift+B) I have:
sjasmplus --lst=z80-sample-program.list --sym=z80-sample-program.labels --fullpath main.asm
make: sjasmplus: Command not found
Makefile:31: recipe for target 'z80-sample-program.sna' failed
make: *** [z80-sample-program.sna] Error 127
The terminal process terminated with exit code: 2

**Comment by maziac** [comment]
Yes, I know.
Actually this is on my todo list (the step-by-step description).
Getting all the pieces to work is quite complex.

I guess you have seen the usage description here https://github.com/maziac/z80-debug/blob/master/documentation/Usage.md .

The error you get there simply means that you have not installed the assembler, sjasmplus.
You can get it from here:
https://github.com/z00m128/sjasmplus

But for debugging the sample program you don't need it as the bin file is already included in git.
It's the file which ends on .sna.

To start you should try to get it to work with ZEsarUX.
I myself use the following command to start ZEsarUX:
Change to the directory where you installed ZEsarUX in a terminal and use e.g.
./zesarux --noconfigfile --machine tbblue --realvideo --tbblue-fast-boot-mode --sna-no-change-machine --enable-esxdos-handler --esxdos-root-dir "/Volumes/....<your_path>.../z80-sample-program/" --enable-remoteprotocol 

Most important is the --enable-remoteprotocol option to enable communication with the z80-debugger.

After ZEsarUx is started try to open the sna file directly from ZEsarUX to see if ZEsarUX is setup correctly.

If that is working:
In vscode press the debug icon and it should run.

**Comment by vito-Z80** [comment]
Thank you for your reply.
I'm more interested in writing zx programs
I have a  sjasmplus, but I don’t know how to attach it to your product.

Could you make a fully working environment with a "vs code portable" ?
https://github.com/garethflowers/vscode-portable

I think it would help those who want your product :)

ср, 18 сент. 2019 г. в 23:36, maziac <notifications@github.com>:

**Comment by maziac** [comment]
If you are looking for sjasmplus that is simple.
Just install sjasmplus and it should work.
It has nothing to so with the IDE it is Just a makefile using sjasmplus.

**Comment by ped7g** [comment]
@vito-Z80 "sjasmplus: Command not found" means the make.exe didn't find sjasmplus.exe (I guess you are on windows). You can either add the path to sjasmplus to your environment variable PATH, or you can check which paths you already have there, maybe there's some path to your "portable" drive handled by the portable tool, and you can put sjasmplus.exe into it, so it will be visible by OS. Or you can edit Makefile and add full path to the sjasmplus executable when launching it, so it will not depend on PATH variable setup.

**Comment by maziac** [comment]
There is now also a more detailed instruction available from Cesar Wagener Moriana:
https://github.com/maziac/z80-debug/tree/master/documentation/extras/Tutorial_ZEsarUX_sjasmplus_z80-debug

It also covers briefly sjasmplus installation.

**Comment by vito-Z80** [comment]
Cool !
